<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Travel;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class TravelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Delete all travels (cascade will handle related bookings and reviews)
        // Cannot use truncate because of foreign key constraints
        // Using delete() which will trigger cascade deletes
        Travel::withoutGlobalScopes()->delete();

        // Get agents
        $jayaTravel = User::where('email', 'jaya.travel@example.com')->first();
        $mitraJaya = User::where('email', 'mitra.jaya@example.com')->first();
        $ekspresUtama = User::where('email', 'ekspres.utama@example.com')->first();
        $nyamanTravel = User::where('email', 'nyaman.travel@example.com')->first();
        $amanJaya = User::where('email', 'aman.jaya@example.com')->first();
        $cepatJaya = User::where('email', 'cepat.jaya@example.com')->first();

        $travels = [
            // Jakarta - Bandung Routes
            [
                'agent_id' => $jayaTravel->id ?? 1,
                'agent_name' => 'Jaya Travel',
                'from_city' => 'Jakarta',
                'to_city' => 'Bandung',
                'depart_time' => '08:00:00',
                'arrival_time' => '11:30:00',
                'duration' => '3.5 jam',
                'price' => 150000,
                'seats' => 8,
                'available_seats' => 8,
                'type' => 'Shuttle Car',
                'rating' => 4.8,
                'reviews_count' => 245,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger']),
                'image' => null,
                'description' => 'Travel nyaman dengan fasilitas lengkap',
                'is_active' => true,
            ],
            [
                'agent_id' => $mitraJaya->id ?? 2,
                'agent_name' => 'Mitra Jaya',
                'from_city' => 'Jakarta',
                'to_city' => 'Bandung',
                'depart_time' => '09:00:00',
                'arrival_time' => '12:30:00',
                'duration' => '3.5 jam',
                'price' => 140000,
                'seats' => 6,
                'available_seats' => 6,
                'type' => 'Private Car',
                'rating' => 4.6,
                'reviews_count' => 189,
                'facilities' => json_encode(['AC', 'Minuman Gratis']),
                'image' => null,
                'description' => 'Private car eksklusif',
                'is_active' => true,
            ],
            // Surabaya - Malang Routes
            [
                'agent_id' => $ekspresUtama->id ?? 3,
                'agent_name' => 'Ekspres Utama',
                'from_city' => 'Surabaya',
                'to_city' => 'Malang',
                'depart_time' => '07:30:00',
                'arrival_time' => '09:30:00',
                'duration' => '2 jam',
                'price' => 80000,
                'seats' => 10,
                'available_seats' => 10,
                'type' => 'Shuttle Car',
                'rating' => 4.7,
                'reviews_count' => 312,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Snack']),
                'image' => null,
                'description' => 'Travel cepat Surabaya-Malang',
                'is_active' => true,
            ],
            // Yogyakarta - Solo Routes
            [
                'agent_id' => $nyamanTravel->id ?? 4,
                'agent_name' => 'Nyaman Travel',
                'from_city' => 'Yogyakarta',
                'to_city' => 'Solo',
                'depart_time' => '10:00:00',
                'arrival_time' => '11:30:00',
                'duration' => '1.5 jam',
                'price' => 120000,
                'seats' => 8,
                'available_seats' => 8,
                'type' => 'Shuttle Car',
                'rating' => 4.5,
                'reviews_count' => 198,
                'facilities' => json_encode(['AC', 'Minuman Gratis']),
                'image' => null,
                'description' => 'Travel antar kota budaya',
                'is_active' => true,
            ],
            // Medan - Kuala Lumpur Routes
            [
                'agent_id' => $amanJaya->id ?? 5,
                'agent_name' => 'Aman Jaya',
                'from_city' => 'Medan',
                'to_city' => 'Kuala Lumpur',
                'depart_time' => '06:00:00',
                'arrival_time' => '18:00:00',
                'duration' => '12 jam',
                'price' => 350000,
                'seats' => 7,
                'available_seats' => 7,
                'type' => 'Shuttle Car',
                'rating' => 4.7,
                'reviews_count' => 267,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Makan', 'Air Mineral']),
                'image' => null,
                'description' => 'Travel internasional Medan-KL',
                'is_active' => true,
            ],
            // Bandung - Garut Routes
            [
                'agent_id' => $cepatJaya->id ?? 6,
                'agent_name' => 'Cepat Jaya',
                'from_city' => 'Bandung',
                'to_city' => 'Garut',
                'depart_time' => '07:00:00',
                'arrival_time' => '09:00:00',
                'duration' => '2 jam',
                'price' => 100000,
                'seats' => 5,
                'available_seats' => 5,
                'type' => 'Private Car',
                'rating' => 4.9,
                'reviews_count' => 156,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Minuman Gratis', 'Snack']),
                'image' => null,
                'description' => 'Private car Bandung-Garut',
                'is_active' => true,
            ],
            // More routes from Jaya Travel
            [
                'agent_id' => $jayaTravel->id ?? 1,
                'agent_name' => 'Jaya Travel',
                'from_city' => 'Jakarta',
                'to_city' => 'Yogyakarta',
                'depart_time' => '06:00:00',
                'arrival_time' => '14:00:00',
                'duration' => '8 jam',
                'price' => 250000,
                'seats' => 12,
                'available_seats' => 12,
                'type' => 'Shuttle Car',
                'rating' => 4.6,
                'reviews_count' => 178,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Makan', 'Air Mineral']),
                'image' => null,
                'description' => 'Travel Jakarta-Yogyakarta dengan fasilitas lengkap',
                'is_active' => true,
            ],
            [
                'agent_id' => $jayaTravel->id ?? 1,
                'agent_name' => 'Jaya Travel',
                'from_city' => 'Jakarta',
                'to_city' => 'Surabaya',
                'depart_time' => '10:00:00',
                'arrival_time' => '22:00:00',
                'duration' => '12 jam',
                'price' => 280000,
                'seats' => 14,
                'available_seats' => 8,
                'type' => 'Shuttle Car',
                'rating' => 4.5,
                'reviews_count' => 203,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Makan', 'Snack', 'Selimut']),
                'image' => null,
                'description' => 'Travel malam Jakarta-Surabaya',
                'is_active' => true,
            ],
            // More routes from Mitra Jaya
            [
                'agent_id' => $mitraJaya->id ?? 2,
                'agent_name' => 'Mitra Jaya',
                'from_city' => 'Jakarta',
                'to_city' => 'Bandung',
                'depart_time' => '14:00:00',
                'arrival_time' => '17:30:00',
                'duration' => '3.5 jam',
                'price' => 145000,
                'seats' => 7,
                'available_seats' => 7,
                'type' => 'Private Car',
                'rating' => 4.7,
                'reviews_count' => 124,
                'facilities' => json_encode(['AC', 'WiFi', 'Minuman Gratis', 'Snack']),
                'image' => null,
                'description' => 'Private car siang Jakarta-Bandung',
                'is_active' => true,
            ],
            // More routes from Ekspres Utama
            [
                'agent_id' => $ekspresUtama->id ?? 3,
                'agent_name' => 'Ekspres Utama',
                'from_city' => 'Surabaya',
                'to_city' => 'Malang',
                'depart_time' => '13:00:00',
                'arrival_time' => '15:00:00',
                'duration' => '2 jam',
                'price' => 85000,
                'seats' => 10,
                'available_seats' => 3,
                'type' => 'Shuttle Car',
                'rating' => 4.8,
                'reviews_count' => 234,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Snack', 'Air Mineral']),
                'image' => null,
                'description' => 'Travel sore Surabaya-Malang',
                'is_active' => true,
            ],
            [
                'agent_id' => $ekspresUtama->id ?? 3,
                'agent_name' => 'Ekspres Utama',
                'from_city' => 'Malang',
                'to_city' => 'Surabaya',
                'depart_time' => '08:00:00',
                'arrival_time' => '10:00:00',
                'duration' => '2 jam',
                'price' => 80000,
                'seats' => 10,
                'available_seats' => 10,
                'type' => 'Shuttle Car',
                'rating' => 4.7,
                'reviews_count' => 189,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Snack']),
                'image' => null,
                'description' => 'Travel pagi Malang-Surabaya',
                'is_active' => true,
            ],
            // More routes from Nyaman Travel
            [
                'agent_id' => $nyamanTravel->id ?? 4,
                'agent_name' => 'Nyaman Travel',
                'from_city' => 'Yogyakarta',
                'to_city' => 'Solo',
                'depart_time' => '14:00:00',
                'arrival_time' => '15:30:00',
                'duration' => '1.5 jam',
                'price' => 115000,
                'seats' => 8,
                'available_seats' => 8,
                'type' => 'Shuttle Car',
                'rating' => 4.6,
                'reviews_count' => 167,
                'facilities' => json_encode(['AC', 'Minuman Gratis', 'Snack']),
                'image' => null,
                'description' => 'Travel siang Yogyakarta-Solo',
                'is_active' => true,
            ],
            [
                'agent_id' => $nyamanTravel->id ?? 4,
                'agent_name' => 'Nyaman Travel',
                'from_city' => 'Solo',
                'to_city' => 'Yogyakarta',
                'depart_time' => '09:00:00',
                'arrival_time' => '10:30:00',
                'duration' => '1.5 jam',
                'price' => 120000,
                'seats' => 8,
                'available_seats' => 5,
                'type' => 'Shuttle Car',
                'rating' => 4.5,
                'reviews_count' => 142,
                'facilities' => json_encode(['AC', 'Minuman Gratis']),
                'image' => null,
                'description' => 'Travel pagi Solo-Yogyakarta',
                'is_active' => true,
            ],
            // More routes from Aman Jaya
            [
                'agent_id' => $amanJaya->id ?? 5,
                'agent_name' => 'Aman Jaya',
                'from_city' => 'Medan',
                'to_city' => 'Berastagi',
                'depart_time' => '07:00:00',
                'arrival_time' => '09:30:00',
                'duration' => '2.5 jam',
                'price' => 120000,
                'seats' => 9,
                'available_seats' => 9,
                'type' => 'Shuttle Car',
                'rating' => 4.8,
                'reviews_count' => 98,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Snack']),
                'image' => null,
                'description' => 'Travel ke dataran tinggi Berastagi',
                'is_active' => true,
            ],
            // More routes from Cepat Jaya
            [
                'agent_id' => $cepatJaya->id ?? 6,
                'agent_name' => 'Cepat Jaya',
                'from_city' => 'Bandung',
                'to_city' => 'Cirebon',
                'depart_time' => '08:00:00',
                'arrival_time' => '10:30:00',
                'duration' => '2.5 jam',
                'price' => 110000,
                'seats' => 6,
                'available_seats' => 6,
                'type' => 'Private Car',
                'rating' => 4.7,
                'reviews_count' => 134,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Minuman Gratis']),
                'image' => null,
                'description' => 'Private car Bandung-Cirebon',
                'is_active' => true,
            ],
            [
                'agent_id' => $cepatJaya->id ?? 6,
                'agent_name' => 'Cepat Jaya',
                'from_city' => 'Bandung',
                'to_city' => 'Jakarta',
                'depart_time' => '15:00:00',
                'arrival_time' => '18:30:00',
                'duration' => '3.5 jam',
                'price' => 155000,
                'seats' => 6,
                'available_seats' => 4,
                'type' => 'Private Car',
                'rating' => 4.9,
                'reviews_count' => 187,
                'facilities' => json_encode(['AC', 'WiFi', 'USB Charger', 'Minuman Gratis', 'Snack']),
                'image' => null,
                'description' => 'Private car sore Bandung-Jakarta',
                'is_active' => true,
            ],
            // Inactive travel example
            [
                'agent_id' => $jayaTravel->id ?? 1,
                'agent_name' => 'Jaya Travel',
                'from_city' => 'Jakarta',
                'to_city' => 'Semarang',
                'depart_time' => '09:00:00',
                'arrival_time' => '15:00:00',
                'duration' => '6 jam',
                'price' => 200000,
                'seats' => 10,
                'available_seats' => 0,
                'type' => 'Shuttle Car',
                'rating' => 4.3,
                'reviews_count' => 89,
                'facilities' => json_encode(['AC', 'WiFi']),
                'image' => null,
                'description' => 'Travel Jakarta-Semarang (Tidak aktif sementara)',
                'is_active' => false,
            ],
        ];

        foreach ($travels as $travel) {
            Travel::create($travel);
        }

        $this->command->info('Data travel berhasil di-seed! Total: ' . count($travels) . ' travel.');
    }
}
